import LayoutAdmin from "@/components/layouts/admin/layout"

export default function Dashboard() {
  return (
    <LayoutAdmin>
      <div className="max-w-xxl xl:mx-2 rounded overflow-hidden shadow-lg">
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores nisi beatae laboriosam accusamus velit quis facere expedita harum dignissimos recusandae voluptatibus, perferendis ducimus minus aperiam blanditiis enim nobis corrupti placeat soluta, tenetur ad nihil? Exercitationem amet repellat quam eum, reiciendis est nesciunt necessitatibus nam eaque id molestias repudiandae, eligendi aliquam animi numquam natus veritatis optio ipsa. Enim repellendus nesciunt modi perspiciatis molestiae tenetur, a iste sit, exercitationem, vitae quibusdam accusamus provident cupiditate! Nam nihil saepe laborum deleniti accusantium. Unde ut laboriosam minus praesentium odit laborum earum fugit rerum quas sapiente quam iste, voluptate cum necessitatibus illum nemo recusandae ipsam ab ipsa tempora optio! Sequi sit laboriosam cum quos mollitia, esse beatae dolor cupiditate voluptatum corporis earum officiis dolore nostrum. Minus a maiores, dolore est quasi reprehenderit. Voluptate, adipisci illo totam saepe accusamus neque a suscipit aut ullam quod tenetur sunt doloribus sequi officiis facilis dicta corporis mollitia. Vero vitae asperiores iusto laborum veritatis, alias eaque dicta! Voluptate ratione unde repellat cupiditate nulla, earum exercitationem dolorum enim quos quas, fugiat architecto obcaecati. Odio numquam quo praesentium inventore nisi quas explicabo fugit corrupti, modi, impedit laboriosam, quis sint at voluptatibus ex. Error repellendus voluptate inventore ea veritatis assumenda numquam odio itaque quos ratione, iste voluptates dignissimos nostrum eius repudiandae delectus tempora reiciendis eaque nam nobis, sed vero, sapiente velit quasi! Quia quibusdam sequi velit iste! In nulla necessitatibus dolor praesentium sint error quibusdam modi reiciendis! Adipisci pariatur culpa debitis delectus mollitia distinctio? Adipisci, distinctio nesciunt sed sit eaque consequatur. Voluptate molestiae beatae deserunt incidunt veritatis assumenda, ab soluta in, enim dolorum reiciendis fuga labore magni recusandae, sed ipsa ipsam laborum? Quae tempora eos unde? Enim ad quam amet velit voluptatum consequatur, iusto eaque culpa maxime, placeat possimus qui doloremque neque dolorem magni dolorum beatae vero laboriosam ratione. Nisi eius iusto inventore possimus?</p>
      </div>
    </LayoutAdmin>
  );
}
